name: Update Contributors

on:
  push:
    branches:
      - main  # Adjust the branch name if necessary

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Contributer Added README.md
        run: |
          contributors=$(git shortlog -s -n | awk '{print "- " $2}')
          echo -e "\n\nContributors:\n$contributors" >> README.md
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git commit -am "Update contributors" --no-gpg-sign
          git push
